### ISSUE TITLE
Wrongly interpreted line break

### ISSUE THREAD

**Issue by wehappyfew** [blacklabelops/logio#1]
The 'n' part from .json is interpreted as line break.

error log:

```
2016-03-28T14:20:48.748274474Z 
/root/.log.io/harvester.conf:8
".log
^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/log.io/bin/log.io-harvester:9:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by blacklabelops** [comment]
Issue fixed and should work with updated readme details.
